name: Build Nethunter Kernel ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git bc bison build-essential ccache curl flex gcc clang lld \
              libssl-dev libncurses5-dev libelf-dev wget zip unzip

      - name: Download kernel source
        run: |
          git clone --depth=1 https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git -b dandelion-q-oss kernel

      - name: Apply defconfig
        run: |
          cp dandelion_defconfig kernel/arch/arm64/configs/dandelion_defconfig

      - name: Build kernel (Image.gz-dtb)
        run: |
          cd kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make dandelion_defconfig
          make -j$(nproc)

      - name: Prepare flashable ZIP
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git ak3
          cp kernel/arch/arm64/boot/Image.gz-dtb ak3/zImage
          cd ak3
          zip -r9 ../nethunter-dandelion-kernel.zip * 

      - name: Upload flashable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: nethunter-dandelion-kernel.zip
          path: nethunter-dandelion-kernel.zip
