name: Build Kernel with HID & WiFi Attacks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential ccache curl flex gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi git libncurses5-dev libssl-dev \
            make python3 unzip wget zip

      - name: Clone Kernel Source
        run: |
          git clone https://github.com/dandelion64-Archives/android_kernel_mediatek_mt6765g.git kernel

      - name: Apply HID patch from NetHunter
        run: |
          cd kernel
          wget https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-kernel/-/raw/master/patches/hid-gadget.patch -O hid.patch
          git apply hid.patch || echo "HID patch applied (or already patched)"

      - name: Enable HID and Wi-Fi drivers in defconfig
        run: |
          cd kernel
          KERNEL_DEFCONFIG=dandelion_defconfig
          make ARCH=arm64 $KERNEL_DEFCONFIG
          scripts/config --file arch/arm64/configs/$KERNEL_DEFCONFIG \
            --enable CONFIG_USB_HID \
            --enable CONFIG_USB_G_HID \
            --enable CONFIG_HID_GENERIC \
            --enable CONFIG_INPUT_UINPUT \
            --module CONFIG_RTL8812AU \
            --module CONFIG_RTL8188EU \
            --module CONFIG_RTL8192EU \
            --module CONFIG_MT7601U \
            --module CONFIG_ATH9K_HTC
          make ARCH=arm64 savedefconfig
          cp defconfig arch/arm64/configs/$KERNEL_DEFCONFIG

      - name: Build kernel (Image.gz-dtb)
        run: |
          cd kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export KCFLAGS=-Wno-error
          export HOSTCFLAGS=-Wno-error
          make dandelion_defconfig
          make -j$(nproc) Image.gz-dtb

      - name: Prepare flashable ZIP
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git AnyKernel
          cp kernel/arch/arm64/boot/Image.gz-dtb AnyKernel/
          cd AnyKernel
          zip -r9 ../Kernel-HID-WiFi.zip ./*

      - name: Upload flashable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-HID-WiFi
          path: Kernel-HID-WiFi.zip
