name: Build Nethunter Kernel ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex gcc clang libssl-dev \
            git kmod libncurses5-dev libelf-dev wget zip unzip

      - name: Build kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          mkdir output
          make O=output dandelion_defconfig
          make O=output -j$(nproc)

      - name: Prepare flashable ZIP
        run: |
          mkdir -p anykernel
          cd anykernel
          git clone https://github.com/osm0sis/AnyKernel3.git .
          cp ../output/arch/arm64/boot/Image.gz-dtb ./Image.gz-dtb
          zip -r9 ../nethunter-kernel.zip * -x .git* README.md *placeholder

      - name: Upload flashable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: nethunter-kernel
          path: nethunter-kernel.zip
