name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential ccache curl flex gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi git libncurses5-dev libssl-dev \
            make python3 unzip wget zip

      - name: Apply HID patch
        run: |
          mkdir -p patches
          wget -O patches/hid-gadget.patch \
            https://raw.githubusercontent.com/pelya/android-keyboard-gadget/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.18.patch
          cp patches/hid-gadget.patch kernel/
          cd kernel
          patch -p1 < hid-gadget.patch

      - name: Build kernel (Image.gz-dtb)
        run: |
          cd kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export KCFLAGS=-Wno-error
          export HOSTCFLAGS=-Wno-error
          make dandelion_defconfig
          make -j$(nproc) Image.gz-dtb

      - name: Prepare flashable ZIP
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git AnyKernel
          cp kernel/arch/arm64/boot/Image.gz-dtb AnyKernel/
          cd AnyKernel
          zip -r9 ../Kernel.zip ./*

      - name: Upload flashable ZIP
        uses: actions/upload-artifact@v3
        with:
          name: Kernel
          path: Kernel.zip
